INSERT INTO kategori_buku(kategori_buku) values ('Publikasi Umum, informasi umum dan komputer');
INSERT INTO kategori_buku(kategori_buku) values ('Bibiliografi');
INSERT INTO kategori_buku(kategori_buku) values ('Perpustakaan dan informasi');
INSERT INTO kategori_buku(kategori_buku) values ('Ensiklopedia dan buku yang memuat fakta-fakta');
INSERT INTO kategori_buku(kategori_buku) values ('Tidak ada klasifikasi (sebelumnya untuk Biografi)');
INSERT INTO kategori_buku(kategori_buku) values ('Majalah dan Jurnal');
INSERT INTO kategori_buku(kategori_buku) values ('Asosiasi, Organisasi dan Museum');
INSERT INTO kategori_buku(kategori_buku) values ('Media massa, junalisme dan publikasi');
INSERT INTO kategori_buku(kategori_buku) values ('Kutipan');
INSERT INTO kategori_buku(kategori_buku) values ('Manuskrip dan buku langka');
INSERT INTO kategori_buku(kategori_buku) values ('Filsafat dan psikologi');
INSERT INTO kategori_buku(kategori_buku) values ('Metafisika');
INSERT INTO kategori_buku(kategori_buku) values ('Epistimologi');
INSERT INTO kategori_buku(kategori_buku) values ('Parapsikologi dan Okultisme');
INSERT INTO kategori_buku(kategori_buku) values ('Pemikiran Filosofis');
INSERT INTO kategori_buku(kategori_buku) values ('Psikologi');
INSERT INTO kategori_buku(kategori_buku) values ('Filosofis Logis');
INSERT INTO kategori_buku(kategori_buku) values ('Etik');
INSERT INTO kategori_buku(kategori_buku) values ('Filosofi kuno, zaman pertengahan, dan filosofi ketimuran');
INSERT INTO kategori_buku(kategori_buku) values ('Filosofi barat modern');
INSERT INTO kategori_buku(kategori_buku) values ('Agama');
INSERT INTO kategori_buku(kategori_buku) values ('Ilmu sosial, sosiologi dan antropologi');
INSERT INTO kategori_buku(kategori_buku) values ('Statistik');
INSERT INTO kategori_buku(kategori_buku) values ('Ilmu politik');
INSERT INTO kategori_buku(kategori_buku) values ('Ekonomi');
INSERT INTO kategori_buku(kategori_buku) values ('Hukum');
INSERT INTO kategori_buku(kategori_buku) values ('Administrasi publik dan ilmu kemiliteran');
INSERT INTO kategori_buku(kategori_buku) values ('Masalah dan layanan sosial');
INSERT INTO kategori_buku(kategori_buku) values ('Pendidikan');
INSERT INTO kategori_buku(kategori_buku) values ('Perdagangan, komunikasi dan transportasi');
INSERT INTO kategori_buku(kategori_buku) values ('Norma, etika dan tradisi');
INSERT INTO kategori_buku(kategori_buku) values ('Bahasa');
INSERT INTO kategori_buku(kategori_buku) values ('Sains');
INSERT INTO kategori_buku(kategori_buku) values ('Matematika');
INSERT INTO kategori_buku(kategori_buku) values ('Astronomi');
INSERT INTO kategori_buku(kategori_buku) values ('Fisika');
INSERT INTO kategori_buku(kategori_buku) values ('Kimia');
INSERT INTO kategori_buku(kategori_buku) values ('Ilmu kebumian dan geologi');
INSERT INTO kategori_buku(kategori_buku) values ('Fosil dan kehidupan prasejarah');
INSERT INTO kategori_buku(kategori_buku) values ('Biologi');
INSERT INTO kategori_buku(kategori_buku) values ('Tanaman');
INSERT INTO kategori_buku(kategori_buku) values ('Zoologi');
INSERT INTO kategori_buku(kategori_buku) values ('Teknologi');
INSERT INTO kategori_buku(kategori_buku) values ('Kesehatan dan Obat-Obatan');
INSERT INTO kategori_buku(kategori_buku) values ('Teknik');
INSERT INTO kategori_buku(kategori_buku) values ('Pertanian');
INSERT INTO kategori_buku(kategori_buku) values ('Managemen Rumah Tangga dan Keluarga');
INSERT INTO kategori_buku(kategori_buku) values ('Manajemen dan Hubungan dengan Publik');
INSERT INTO kategori_buku(kategori_buku) values ('Teknik Kimia');
INSERT INTO kategori_buku(kategori_buku) values ('Manufaktur');
INSERT INTO kategori_buku(kategori_buku) values ('Manufaktur untuk Keperluan Khusus');
INSERT INTO kategori_buku(kategori_buku) values ('Konstruksi');
INSERT INTO kategori_buku(kategori_buku) values ('Kesenian dan rekreasi');
INSERT INTO kategori_buku(kategori_buku) values ('Perencanaan dan Arsitektur Lanskap');
INSERT INTO kategori_buku(kategori_buku) values ('Arsitektur');
INSERT INTO kategori_buku(kategori_buku) values ('Patung, Keramik dan Seni Metal');
INSERT INTO kategori_buku(kategori_buku) values ('Seni Grafis dan Dekoratif');
INSERT INTO kategori_buku(kategori_buku) values ('Lukisan');
INSERT INTO kategori_buku(kategori_buku) values ('Percetakan');
INSERT INTO kategori_buku(kategori_buku) values ('Fotografi, Film, Video');
INSERT INTO kategori_buku(kategori_buku) values ('Musik');
INSERT INTO kategori_buku(kategori_buku) values ('Olahraga, Permainan dan Hiburan');
INSERT INTO kategori_buku(kategori_buku) values ('Literatur, Sastra, Retorika dan Kritik');
INSERT INTO kategori_buku(kategori_buku) values ('Sejarah');
INSERT INTO kategori_buku(kategori_buku) values ('Geografi dan Perjalanan');
INSERT INTO kategori_buku(kategori_buku) values ('Biografi dan Asal-Usul');
INSERT INTO kategori_buku(kategori_buku) values ('Sejarah Dunia Lama');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Eropa');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Asia');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Afrika');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Amerika Utara');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Amerika Selatan');
INSERT INTO kategori_buku(kategori_buku) values ('Asal-Usul Wilayah Lain');

COMMIT;
